# Build script for Travis CI
#

# use fast-boot container-based hosts
sudo: false 
dist: trusty

# no need to check for oracle's java
language: java
jdk: openjdk8

# speed up builds by caching maven local repository
cache:
  directories:
  - "$HOME/.m2/repository"

# as agreed in our SOP
branches:
  only:
  - master
  - development

# added to make logs look cleaner, crisper, certified fresh
before_install: unset _JAVA_OPTIONS 

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: ./compile.sh
after_success:
  - ./run_tests.sh