# Build script for Travis CI
#

# use fast-boot container-based hosts
sudo: false 
dist: trusty

# no need to check for oracle's java
language: java
jdk: openjdk8

before_install:
  - cp travis/settings.xml ~/.m2/settings.xml
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: ./compile.sh
after_success:
  - ./run_tests.sh